### ISSUE TITLE
[Cmake] AssimpModelLoader unable link new version of Assimp

### ISSUE THREAD

**Issue by barvirm** [Rendering-FIT/GPUEngine#8]
GPUEngine master branch
Assimp >= 4.1.0 tested on master branch
Visual studio 2017 Win64 
Build fail on LNK1181 - cannot open input file assimp.lib

For fixing this issue need to be change line 52 in AssimpModelLoaderConfig.cmake
From
target_link_libraries(${MODULE_NAME} INTERFACE ste geSG glm assimp)
To
target_link_libraries(${MODULE_NAME} INTERFACE ste geSG glm assimp::assimp)

**Comment by forry** [comment]
Well that (assimp target name) was intended, but still we have to adjust this to assimp::assimp since Dormon was the one that propagated that change to assimp repo. But it may affect more than one example/application.
